// Generated by CIRCT unknown git version
module loop_array(	// ./comp/hw.mlir:2:3
    input  [31:0] n,	// ./comp/hw.mlir:2:28
    k,	// ./comp/hw.mlir:2:41
    c_loadData,	// ./comp/hw.mlir:2:54
    input         start,	// ./comp/hw.mlir:2:76
    clk,	// ./comp/hw.mlir:2:92
    rst,	// ./comp/hw.mlir:2:106
    output        out0,	// ./comp/hw.mlir:2:121
    c_loadEn,	// ./comp/hw.mlir:2:136
    output [31:0] c_loadAddr,	// ./comp/hw.mlir:2:155
    output        c_storeEn,	// ./comp/hw.mlir:2:177
    output [31:0] c_storeAddr,	// ./comp/hw.mlir:2:197
    c_storeData	// ./comp/hw.mlir:2:220
  );

  wire        _tehb5_outs;	// ./comp/hw.mlir:52:19
  wire        _oehb6_outs;	// ./comp/hw.mlir:51:19
  wire        _tehb3_outs;	// ./comp/hw.mlir:50:19
  wire [31:0] _tehb1_outs;	// ./comp/hw.mlir:49:19
  wire [31:0] _oehb8_outs;	// ./comp/hw.mlir:48:19
  wire [31:0] _addi2_result;	// ./comp/hw.mlir:47:21
  wire [31:0] _lsq_store0_addrOut;	// ./comp/hw.mlir:46:50
  wire [31:0] _lsq_store0_dataToMem;	// ./comp/hw.mlir:46:50
  wire [31:0] _addi0_result;	// ./comp/hw.mlir:45:21
  wire [31:0] _lsq_load0_addrOut;	// ./comp/hw.mlir:44:46
  wire [31:0] _lsq_load0_dataOut;	// ./comp/hw.mlir:44:46
  wire [31:0] _addi1_result;	// ./comp/hw.mlir:43:21
  wire [31:0] _extsi1_outs;	// ./comp/hw.mlir:42:20
  wire [1:0]  _constant5_outs;	// ./comp/hw.mlir:41:23
  wire        _source1_outs;	// ./comp/hw.mlir:40:21
  wire [31:0] _constant4_outs;	// ./comp/hw.mlir:39:23
  wire        _source0_outs;	// ./comp/hw.mlir:38:21
  wire        _fork7_outs_0;	// ./comp/hw.mlir:37:36
  wire        _fork7_outs_1;	// ./comp/hw.mlir:37:36
  wire [31:0] _fork6_outs_0;	// ./comp/hw.mlir:36:51
  wire [31:0] _fork6_outs_1;	// ./comp/hw.mlir:36:51
  wire [31:0] _fork6_outs_2;	// ./comp/hw.mlir:36:51
  wire [31:0] _tehb2_outs;	// ./comp/hw.mlir:35:19
  wire [31:0] _oehb9_outs;	// ./comp/hw.mlir:34:19
  wire [31:0] _fork5_outs_0;	// ./comp/hw.mlir:33:36
  wire [31:0] _fork5_outs_1;	// ./comp/hw.mlir:33:36
  wire [31:0] _tehb0_outs;	// ./comp/hw.mlir:32:19
  wire [31:0] _oehb7_outs;	// ./comp/hw.mlir:31:19
  wire        _cond_br4_trueOut;	// ./comp/hw.mlir:30:45
  wire        _cond_br4_falseOut;	// ./comp/hw.mlir:30:45
  wire        _oehb3_outs;	// ./comp/hw.mlir:29:19
  wire [31:0] _cond_br3_trueOut;	// ./comp/hw.mlir:27:45
  wire [31:0] _cond_br3_falseOut;	// ./comp/hw.mlir:27:45
  wire [31:0] _cond_br2_trueOut;	// ./comp/hw.mlir:25:45
  wire [31:0] _cond_br2_falseOut;	// ./comp/hw.mlir:25:45
  wire [31:0] _cond_br1_trueOut;	// ./comp/hw.mlir:23:45
  wire [31:0] _cond_br1_falseOut;	// ./comp/hw.mlir:23:45
  wire [31:0] _oehb1_outs;	// ./comp/hw.mlir:22:19
  wire        _fork4_outs_0;	// ./comp/hw.mlir:21:66
  wire        _fork4_outs_1;	// ./comp/hw.mlir:21:66
  wire        _fork4_outs_2;	// ./comp/hw.mlir:21:66
  wire        _fork4_outs_3;	// ./comp/hw.mlir:21:66
  wire        _oehb5_outs;	// ./comp/hw.mlir:20:19
  wire        _cmpi0_result;	// ./comp/hw.mlir:19:21
  wire        _fork3_outs_0;	// ./comp/hw.mlir:18:51
  wire        _fork3_outs_1;	// ./comp/hw.mlir:18:51
  wire        _fork3_outs_2;	// ./comp/hw.mlir:18:51
  wire        _oehb4_outs;	// ./comp/hw.mlir:17:19
  wire        _control_merge3_outs;	// ./comp/hw.mlir:16:51
  wire        _control_merge3_index;	// ./comp/hw.mlir:16:51
  wire        _oehb10_outs;	// ./comp/hw.mlir:15:20
  wire [31:0] _fork2_outs_0;	// ./comp/hw.mlir:14:36
  wire [31:0] _fork2_outs_1;	// ./comp/hw.mlir:14:36
  wire [31:0] _oehb2_outs;	// ./comp/hw.mlir:13:19
  wire [31:0] _mux2_outs;	// ./comp/hw.mlir:12:18
  wire [31:0] _mux1_outs;	// ./comp/hw.mlir:11:18
  wire [31:0] _fork1_outs_0;	// ./comp/hw.mlir:10:36
  wire [31:0] _fork1_outs_1;	// ./comp/hw.mlir:10:36
  wire [31:0] _oehb0_outs;	// ./comp/hw.mlir:9:19
  wire [31:0] _mux0_outs;	// ./comp/hw.mlir:8:18
  wire [31:0] _tehb4_outs;	// ./comp/hw.mlir:7:19
  wire [31:0] _extsi2_outs;	// ./comp/hw.mlir:6:20
  wire [1:0]  _constant1_outs;	// ./comp/hw.mlir:5:23
  wire        _fork0_outs_0;	// ./comp/hw.mlir:4:36
  wire        _fork0_outs_1;	// ./comp/hw.mlir:4:36
  wire [31:0] _lsq0_ldData_0;	// ./comp/hw.mlir:3:116
  wire        _lsq0_memDone;	// ./comp/hw.mlir:3:116
  handshake_lsq lsq0 (	// ./comp/hw.mlir:3:116
                  .loadData  (c_loadData),
                  .ctrl_0    (_fork7_outs_1),	// ./comp/hw.mlir:37:36
                  .ldAddr_0  (_lsq_load0_addrOut),	// ./comp/hw.mlir:44:46
                  .stAddr_0  (_lsq_store0_addrOut),	// ./comp/hw.mlir:46:50
                  .stData_0  (_lsq_store0_dataToMem),	// ./comp/hw.mlir:46:50
                  .clk       (clk),
                  .rst       (rst),
                  .ldData_0  (_lsq0_ldData_0),
                  .memDone   (_lsq0_memDone),
                  .loadEn    (c_loadEn),
                  .loadAddr  (c_loadAddr),
                  .storeEn   (c_storeEn),
                  .storeAddr (c_storeAddr),
                  .storeData (c_storeData)
                );	// ./comp/hw.mlir:3:116
  handshake_fork #(
                   .SIZE(2),
                   .DATA_WIDTH(0)
                 ) fork0 (	// ./comp/hw.mlir:4:36
                   .ins    (start),
                   .clk    (clk),
                   .rst    (rst),
                   .outs_0 (_fork0_outs_0),
                   .outs_1 (_fork0_outs_1)
                 );	// ./comp/hw.mlir:4:36
  handshake_constant #(
                       .VALUE("01"),
                       .DATA_WIDTH(2)
                     ) constant1 (	// ./comp/hw.mlir:5:23
                       .ctrl (_fork0_outs_1),	// ./comp/hw.mlir:4:36
                       .clk  (clk),
                       .rst  (rst),
                       .outs (_constant1_outs)
                     );	// ./comp/hw.mlir:5:23
  arith_extsi #(
                .INPUT_WIDTH(2),
                .OUTPUT_WIDTH(32)
              ) extsi2 (	// ./comp/hw.mlir:6:20
                .ins  (_constant1_outs),	// ./comp/hw.mlir:5:23
                .clk  (clk),
                .rst  (rst),
                .outs (_extsi2_outs)
              );	// ./comp/hw.mlir:6:20
  handshake_tehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) tehb4 (	// ./comp/hw.mlir:7:19
                   .ins  (_addi2_result),	// ./comp/hw.mlir:47:21
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_tehb4_outs)
                 );	// ./comp/hw.mlir:7:19
  handshake_mux #(
                  .SIZE(2),
                  .DATA_WIDTH(32),
                  .SELECT_WIDTH(1)
                ) mux0 (	// ./comp/hw.mlir:8:18
                  .index (_fork3_outs_2),	// ./comp/hw.mlir:18:51
                  .ins_0 (_tehb4_outs),	// ./comp/hw.mlir:7:19
                  .ins_1 (_extsi2_outs),	// ./comp/hw.mlir:6:20
                  .clk   (clk),
                  .rst   (rst),
                  .outs  (_mux0_outs)
                );	// ./comp/hw.mlir:8:18
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) oehb0 (	// ./comp/hw.mlir:9:19
                   .ins  (_mux0_outs),	// ./comp/hw.mlir:8:18
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb0_outs)
                 );	// ./comp/hw.mlir:9:19
  handshake_fork #(
                   .SIZE(2),
                   .DATA_WIDTH(32)
                 ) fork1 (	// ./comp/hw.mlir:10:36
                   .ins    (_oehb0_outs),	// ./comp/hw.mlir:9:19
                   .clk    (clk),
                   .rst    (rst),
                   .outs_0 (_fork1_outs_0),
                   .outs_1 (_fork1_outs_1)
                 );	// ./comp/hw.mlir:10:36
  handshake_mux #(
                  .SIZE(2),
                  .DATA_WIDTH(32),
                  .SELECT_WIDTH(1)
                ) mux1 (	// ./comp/hw.mlir:11:18
                  .index (_fork3_outs_1),	// ./comp/hw.mlir:18:51
                  .ins_0 (_fork5_outs_0),	// ./comp/hw.mlir:33:36
                  .ins_1 (k),
                  .clk   (clk),
                  .rst   (rst),
                  .outs  (_mux1_outs)
                );	// ./comp/hw.mlir:11:18
  handshake_mux #(
                  .SIZE(2),
                  .DATA_WIDTH(32),
                  .SELECT_WIDTH(1)
                ) mux2 (	// ./comp/hw.mlir:12:18
                  .index (_fork3_outs_0),	// ./comp/hw.mlir:18:51
                  .ins_0 (_tehb1_outs),	// ./comp/hw.mlir:49:19
                  .ins_1 (n),
                  .clk   (clk),
                  .rst   (rst),
                  .outs  (_mux2_outs)
                );	// ./comp/hw.mlir:12:18
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) oehb2 (	// ./comp/hw.mlir:13:19
                   .ins  (_mux2_outs),	// ./comp/hw.mlir:12:18
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb2_outs)
                 );	// ./comp/hw.mlir:13:19
  handshake_fork #(
                   .SIZE(2),
                   .DATA_WIDTH(32)
                 ) fork2 (	// ./comp/hw.mlir:14:36
                   .ins    (_oehb2_outs),	// ./comp/hw.mlir:13:19
                   .clk    (clk),
                   .rst    (rst),
                   .outs_0 (_fork2_outs_0),
                   .outs_1 (_fork2_outs_1)
                 );	// ./comp/hw.mlir:14:36
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(0)
                 ) oehb10 (	// ./comp/hw.mlir:15:20
                   .ins  (_tehb3_outs),	// ./comp/hw.mlir:50:19
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb10_outs)
                 );	// ./comp/hw.mlir:15:20
  handshake_control_merge #(
                            .SIZE(2),
                            .DATA_WIDTH(0),
                            .INDEX_WIDTH(1)
                          ) control_merge3 (	// ./comp/hw.mlir:16:51
                            .ins_0 (_oehb10_outs),	// ./comp/hw.mlir:15:20
                            .ins_1 (_fork0_outs_0),	// ./comp/hw.mlir:4:36
                            .clk   (clk),
                            .rst   (rst),
                            .outs  (_control_merge3_outs),
                            .index (_control_merge3_index)
                          );	// ./comp/hw.mlir:16:51
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(1)
                 ) oehb4 (	// ./comp/hw.mlir:17:19
                   .ins  (_control_merge3_index),	// ./comp/hw.mlir:16:51
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb4_outs)
                 );	// ./comp/hw.mlir:17:19
  handshake_fork #(
                   .SIZE(3),
                   .DATA_WIDTH(1)
                 ) fork3 (	// ./comp/hw.mlir:18:51
                   .ins    (_oehb4_outs),	// ./comp/hw.mlir:17:19
                   .clk    (clk),
                   .rst    (rst),
                   .outs_0 (_fork3_outs_0),
                   .outs_1 (_fork3_outs_1),
                   .outs_2 (_fork3_outs_2)
                 );	// ./comp/hw.mlir:18:51
  arith_cmpi #(
               .PREDICATE("ult"),
               .DATA_WIDTH(32)
             ) cmpi0 (	// ./comp/hw.mlir:19:21
               .lhs    (_fork1_outs_1),	// ./comp/hw.mlir:10:36
               .rhs    (_fork2_outs_1),	// ./comp/hw.mlir:14:36
               .clk    (clk),
               .rst    (rst),
               .result (_cmpi0_result)
             );	// ./comp/hw.mlir:19:21
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(1)
                 ) oehb5 (	// ./comp/hw.mlir:20:19
                   .ins  (_cmpi0_result),	// ./comp/hw.mlir:19:21
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb5_outs)
                 );	// ./comp/hw.mlir:20:19
  handshake_fork #(
                   .SIZE(4),
                   .DATA_WIDTH(1)
                 ) fork4 (	// ./comp/hw.mlir:21:66
                   .ins    (_oehb5_outs),	// ./comp/hw.mlir:20:19
                   .clk    (clk),
                   .rst    (rst),
                   .outs_0 (_fork4_outs_0),
                   .outs_1 (_fork4_outs_1),
                   .outs_2 (_fork4_outs_2),
                   .outs_3 (_fork4_outs_3)
                 );	// ./comp/hw.mlir:21:66
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) oehb1 (	// ./comp/hw.mlir:22:19
                   .ins  (_mux1_outs),	// ./comp/hw.mlir:11:18
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb1_outs)
                 );	// ./comp/hw.mlir:22:19
  handshake_cond_br #(
                      .DATA_WIDTH(32)
                    ) cond_br1 (	// ./comp/hw.mlir:23:45
                      .condition (_fork4_outs_3),	// ./comp/hw.mlir:21:66
                      .data      (_oehb1_outs),	// ./comp/hw.mlir:22:19
                      .clk       (clk),
                      .rst       (rst),
                      .trueOut   (_cond_br1_trueOut),
                      .falseOut  (_cond_br1_falseOut)
                    );	// ./comp/hw.mlir:23:45
  handshake_sink #(
                   .DATA_WIDTH(32)
                 ) sink0 (	// ./comp/hw.mlir:24:5
                   .ins (_cond_br1_falseOut),	// ./comp/hw.mlir:23:45
                   .clk (clk),
                   .rst (rst)
                 );	// ./comp/hw.mlir:24:5
  handshake_cond_br #(
                      .DATA_WIDTH(32)
                    ) cond_br2 (	// ./comp/hw.mlir:25:45
                      .condition (_fork4_outs_2),	// ./comp/hw.mlir:21:66
                      .data      (_fork2_outs_0),	// ./comp/hw.mlir:14:36
                      .clk       (clk),
                      .rst       (rst),
                      .trueOut   (_cond_br2_trueOut),
                      .falseOut  (_cond_br2_falseOut)
                    );	// ./comp/hw.mlir:25:45
  handshake_sink #(
                   .DATA_WIDTH(32)
                 ) sink1 (	// ./comp/hw.mlir:26:5
                   .ins (_cond_br2_falseOut),	// ./comp/hw.mlir:25:45
                   .clk (clk),
                   .rst (rst)
                 );	// ./comp/hw.mlir:26:5
  handshake_cond_br #(
                      .DATA_WIDTH(32)
                    ) cond_br3 (	// ./comp/hw.mlir:27:45
                      .condition (_fork4_outs_1),	// ./comp/hw.mlir:21:66
                      .data      (_fork1_outs_0),	// ./comp/hw.mlir:10:36
                      .clk       (clk),
                      .rst       (rst),
                      .trueOut   (_cond_br3_trueOut),
                      .falseOut  (_cond_br3_falseOut)
                    );	// ./comp/hw.mlir:27:45
  handshake_sink #(
                   .DATA_WIDTH(32)
                 ) sink2 (	// ./comp/hw.mlir:28:5
                   .ins (_cond_br3_falseOut),	// ./comp/hw.mlir:27:45
                   .clk (clk),
                   .rst (rst)
                 );	// ./comp/hw.mlir:28:5
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(0)
                 ) oehb3 (	// ./comp/hw.mlir:29:19
                   .ins  (_control_merge3_outs),	// ./comp/hw.mlir:16:51
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb3_outs)
                 );	// ./comp/hw.mlir:29:19
  handshake_cond_br #(
                      .DATA_WIDTH(0)
                    ) cond_br4 (	// ./comp/hw.mlir:30:45
                      .condition (_fork4_outs_0),	// ./comp/hw.mlir:21:66
                      .data      (_oehb3_outs),	// ./comp/hw.mlir:29:19
                      .clk       (clk),
                      .rst       (rst),
                      .trueOut   (_cond_br4_trueOut),
                      .falseOut  (_cond_br4_falseOut)
                    );	// ./comp/hw.mlir:30:45
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) oehb7 (	// ./comp/hw.mlir:31:19
                   .ins  (_cond_br1_trueOut),	// ./comp/hw.mlir:23:45
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb7_outs)
                 );	// ./comp/hw.mlir:31:19
  handshake_tehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) tehb0 (	// ./comp/hw.mlir:32:19
                   .ins  (_oehb7_outs),	// ./comp/hw.mlir:31:19
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_tehb0_outs)
                 );	// ./comp/hw.mlir:32:19
  handshake_fork #(
                   .SIZE(2),
                   .DATA_WIDTH(32)
                 ) fork5 (	// ./comp/hw.mlir:33:36
                   .ins    (_tehb0_outs),	// ./comp/hw.mlir:32:19
                   .clk    (clk),
                   .rst    (rst),
                   .outs_0 (_fork5_outs_0),
                   .outs_1 (_fork5_outs_1)
                 );	// ./comp/hw.mlir:33:36
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) oehb9 (	// ./comp/hw.mlir:34:19
                   .ins  (_cond_br3_trueOut),	// ./comp/hw.mlir:27:45
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb9_outs)
                 );	// ./comp/hw.mlir:34:19
  handshake_tehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) tehb2 (	// ./comp/hw.mlir:35:19
                   .ins  (_oehb9_outs),	// ./comp/hw.mlir:34:19
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_tehb2_outs)
                 );	// ./comp/hw.mlir:35:19
  handshake_fork #(
                   .SIZE(3),
                   .DATA_WIDTH(32)
                 ) fork6 (	// ./comp/hw.mlir:36:51
                   .ins    (_tehb2_outs),	// ./comp/hw.mlir:35:19
                   .clk    (clk),
                   .rst    (rst),
                   .outs_0 (_fork6_outs_0),
                   .outs_1 (_fork6_outs_1),
                   .outs_2 (_fork6_outs_2)
                 );	// ./comp/hw.mlir:36:51
  handshake_fork #(
                   .SIZE(2),
                   .DATA_WIDTH(0)
                 ) fork7 (	// ./comp/hw.mlir:37:36
                   .ins    (_cond_br4_trueOut),	// ./comp/hw.mlir:30:45
                   .clk    (clk),
                   .rst    (rst),
                   .outs_0 (_fork7_outs_0),
                   .outs_1 (_fork7_outs_1)
                 );	// ./comp/hw.mlir:37:36
  handshake_source source0 (	// ./comp/hw.mlir:38:21
                     .clk  (clk),
                     .rst  (rst),
                     .outs (_source0_outs)
                   );	// ./comp/hw.mlir:38:21
  handshake_constant #(
                       .VALUE("11111111111111111111111111111111"),
                       .DATA_WIDTH(32)
                     ) constant4 (	// ./comp/hw.mlir:39:23
                       .ctrl (_source0_outs),	// ./comp/hw.mlir:38:21
                       .clk  (clk),
                       .rst  (rst),
                       .outs (_constant4_outs)
                     );	// ./comp/hw.mlir:39:23
  handshake_source source1 (	// ./comp/hw.mlir:40:21
                     .clk  (clk),
                     .rst  (rst),
                     .outs (_source1_outs)
                   );	// ./comp/hw.mlir:40:21
  handshake_constant #(
                       .VALUE("01"),
                       .DATA_WIDTH(2)
                     ) constant5 (	// ./comp/hw.mlir:41:23
                       .ctrl (_source1_outs),	// ./comp/hw.mlir:40:21
                       .clk  (clk),
                       .rst  (rst),
                       .outs (_constant5_outs)
                     );	// ./comp/hw.mlir:41:23
  arith_extsi #(
                .INPUT_WIDTH(2),
                .OUTPUT_WIDTH(32)
              ) extsi1 (	// ./comp/hw.mlir:42:20
                .ins  (_constant5_outs),	// ./comp/hw.mlir:41:23
                .clk  (clk),
                .rst  (rst),
                .outs (_extsi1_outs)
              );	// ./comp/hw.mlir:42:20
  arith_addi #(
               .DATA_WIDTH(32)
             ) addi1 (	// ./comp/hw.mlir:43:21
               .lhs    (_fork6_outs_2),	// ./comp/hw.mlir:36:51
               .rhs    (_constant4_outs),	// ./comp/hw.mlir:39:23
               .clk    (clk),
               .rst    (rst),
               .result (_addi1_result)
             );	// ./comp/hw.mlir:43:21
  handshake_lsq_load #(
                       .DATA_WIDTH(32),
                       .ADDR_WIDTH(32)
                     ) lsq_load0 (	// ./comp/hw.mlir:44:46
                       .addrIn      (_addi1_result),	// ./comp/hw.mlir:43:21
                       .dataFromMem (_lsq0_ldData_0),	// ./comp/hw.mlir:3:116
                       .clk         (clk),
                       .rst         (rst),
                       .addrOut     (_lsq_load0_addrOut),
                       .dataOut     (_lsq_load0_dataOut)
                     );	// ./comp/hw.mlir:44:46
  arith_addi #(
               .DATA_WIDTH(32)
             ) addi0 (	// ./comp/hw.mlir:45:21
               .lhs    (_fork5_outs_1),	// ./comp/hw.mlir:33:36
               .rhs    (_lsq_load0_dataOut),	// ./comp/hw.mlir:44:46
               .clk    (clk),
               .rst    (rst),
               .result (_addi0_result)
             );	// ./comp/hw.mlir:45:21
  handshake_lsq_store #(
                        .DATA_WIDTH(32),
                        .ADDR_WIDTH(32)
                      ) lsq_store0 (	// ./comp/hw.mlir:46:50
                        .addrIn    (_fork6_outs_1),	// ./comp/hw.mlir:36:51
                        .dataIn    (_addi0_result),	// ./comp/hw.mlir:45:21
                        .clk       (clk),
                        .rst       (rst),
                        .addrOut   (_lsq_store0_addrOut),
                        .dataToMem (_lsq_store0_dataToMem)
                      );	// ./comp/hw.mlir:46:50
  arith_addi #(
               .DATA_WIDTH(32)
             ) addi2 (	// ./comp/hw.mlir:47:21
               .lhs    (_fork6_outs_0),	// ./comp/hw.mlir:36:51
               .rhs    (_extsi1_outs),	// ./comp/hw.mlir:42:20
               .clk    (clk),
               .rst    (rst),
               .result (_addi2_result)
             );	// ./comp/hw.mlir:47:21
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) oehb8 (	// ./comp/hw.mlir:48:19
                   .ins  (_cond_br2_trueOut),	// ./comp/hw.mlir:25:45
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb8_outs)
                 );	// ./comp/hw.mlir:48:19
  handshake_tehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(32)
                 ) tehb1 (	// ./comp/hw.mlir:49:19
                   .ins  (_oehb8_outs),	// ./comp/hw.mlir:48:19
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_tehb1_outs)
                 );	// ./comp/hw.mlir:49:19
  handshake_tehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(0)
                 ) tehb3 (	// ./comp/hw.mlir:50:19
                   .ins  (_fork7_outs_0),	// ./comp/hw.mlir:37:36
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_tehb3_outs)
                 );	// ./comp/hw.mlir:50:19
  handshake_oehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(0)
                 ) oehb6 (	// ./comp/hw.mlir:51:19
                   .ins  (_cond_br4_falseOut),	// ./comp/hw.mlir:30:45
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_oehb6_outs)
                 );	// ./comp/hw.mlir:51:19
  handshake_tehb #(
                   .SLOTS(1),
                   .DATA_WIDTH(0)
                 ) tehb5 (	// ./comp/hw.mlir:52:19
                   .ins  (_oehb6_outs),	// ./comp/hw.mlir:51:19
                   .clk  (clk),
                   .rst  (rst),
                   .outs (_tehb5_outs)
                 );	// ./comp/hw.mlir:52:19
  handshake_end #(
                  .DATA_WIDTH(0),
                  .NUM_MEMORIES(1)
                ) end0 (	// ./comp/hw.mlir:53:20
                  .ins_0     (_tehb5_outs),	// ./comp/hw.mlir:52:19
                  .memDone_0 (_lsq0_memDone),	// ./comp/hw.mlir:3:116
                  .clk       (clk),
                  .rst       (rst),
                  .outs_0    (out0)
                );	// ./comp/hw.mlir:53:20
endmodule

// external module handshake_lsq

// external module handshake_fork

// external module handshake_constant

// external module arith_extsi

// external module handshake_tehb

// external module handshake_mux

// external module handshake_oehb

// external module handshake_fork

// external module handshake_oehb

// external module handshake_control_merge

// external module handshake_oehb

// external module handshake_fork

// external module arith_cmpi

// external module handshake_fork

// external module handshake_cond_br

// external module handshake_sink

// external module handshake_cond_br

// external module handshake_fork

// external module handshake_source

// external module handshake_constant

// external module arith_addi

// external module handshake_lsq_load

// external module handshake_lsq_store

// external module handshake_tehb

// external module handshake_end

// external module mem_to_bram_32_32

module loop_array_wrapper(	// ./comp/hw.mlir:82:3
    input  [31:0] n,	// ./comp/hw.mlir:82:36
    k,	// ./comp/hw.mlir:82:49
    c_mem_dout0,	// ./comp/hw.mlir:82:62
    c_mem_dout1,	// ./comp/hw.mlir:82:85
    input         start,	// ./comp/hw.mlir:82:108
    clk,	// ./comp/hw.mlir:82:124
    rst,	// ./comp/hw.mlir:82:138
    output        out0,	// ./comp/hw.mlir:82:153
    c_ce0,	// ./comp/hw.mlir:82:168
    c_we0,	// ./comp/hw.mlir:82:184
    output [31:0] c_address0,	// ./comp/hw.mlir:82:200
    c_mem_din0,	// ./comp/hw.mlir:82:222
    output        c_ce1,	// ./comp/hw.mlir:82:244
    c_we1,	// ./comp/hw.mlir:82:260
    output [31:0] c_address1,	// ./comp/hw.mlir:82:276
    c_mem_din1	// ./comp/hw.mlir:82:298
  );

  wire        _loop_array_wrapped_c_loadEn;	// ./comp/hw.mlir:84:191
  wire [31:0] _loop_array_wrapped_c_loadAddr;	// ./comp/hw.mlir:84:191
  wire        _loop_array_wrapped_c_storeEn;	// ./comp/hw.mlir:84:191
  wire [31:0] _loop_array_wrapped_c_storeAddr;	// ./comp/hw.mlir:84:191
  wire [31:0] _loop_array_wrapped_c_storeData;	// ./comp/hw.mlir:84:191
  wire [31:0] _mem_to_bram_converter_c_loadData;	// ./comp/hw.mlir:83:301
  mem_to_bram_32_32 mem_to_bram_converter_c (	// ./comp/hw.mlir:83:301
                      .loadEn    (_loop_array_wrapped_c_loadEn),	// ./comp/hw.mlir:84:191
                      .loadAddr  (_loop_array_wrapped_c_loadAddr),	// ./comp/hw.mlir:84:191
                      .storeEn   (_loop_array_wrapped_c_storeEn),	// ./comp/hw.mlir:84:191
                      .storeAddr (_loop_array_wrapped_c_storeAddr),	// ./comp/hw.mlir:84:191
                      .storeData (_loop_array_wrapped_c_storeData),	// ./comp/hw.mlir:84:191
                      .mem_dout0 (c_mem_dout0),
                      .mem_dout1 (c_mem_dout1),
                      .ce0       (c_ce0),
                      .we0       (c_we0),
                      .address0  (c_address0),
                      .mem_din0  (c_mem_din0),
                      .ce1       (c_ce1),
                      .we1       (c_we1),
                      .address1  (c_address1),
                      .mem_din1  (c_mem_din1),
                      .loadData  (_mem_to_bram_converter_c_loadData)
                    );	// ./comp/hw.mlir:83:301
  loop_array loop_array_wrapped (	// ./comp/hw.mlir:84:191
               .n           (n),
               .k           (k),
               .c_loadData  (_mem_to_bram_converter_c_loadData),	// ./comp/hw.mlir:83:301
               .start       (start),
               .clk         (clk),
               .rst         (rst),
               .out0        (out0),
               .c_loadEn    (_loop_array_wrapped_c_loadEn),
               .c_loadAddr  (_loop_array_wrapped_c_loadAddr),
               .c_storeEn   (_loop_array_wrapped_c_storeEn),
               .c_storeAddr (_loop_array_wrapped_c_storeAddr),
               .c_storeData (_loop_array_wrapped_c_storeData)
             );	// ./comp/hw.mlir:84:191
endmodule
