/* Generated by Yosys 0.50 (git sha1 b5170e139, g++ 12.2.1 -fPIC -O3) */

module IO(from_fabric, to_fabric, in, out);
  input [31:0] from_fabric;
  wire [31:0] from_fabric;
  input [31:0] in;
  wire [31:0] in;
  output [31:0] out;
  wire [31:0] out;
  output [31:0] to_fabric;
  wire [31:0] to_fabric;
  assign out = from_fabric;
  assign to_fabric = in;
endmodule

