#RES_reg_unit:RES_en

#RES_reg_unit:RES_reg_in
ALU:data_out 32 reg_unit:reg_in 32 3 

#RES_reg_unit:RES_rst

#N_pred_reg_unit:N_pred_en

#N_pred_reg_unit:N_pred_reg_in

#N_pred_reg_unit:N_pred_rst

#E_pred_reg_unit:E_pred_en

#E_pred_reg_unit:E_pred_reg_in

#E_pred_reg_unit:E_pred_rst

#S_pred_reg_unit:S_pred_en

#S_pred_reg_unit:S_pred_reg_in

#S_pred_reg_unit:S_pred_rst

#W_pred_reg_unit:W_pred_en

#W_pred_reg_unit:W_pred_reg_in

#W_pred_reg_unit:W_pred_rst

#Mem:reset

