/* Generated by Yosys 0.47+56 (git sha1 a22ff47d6, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* hdlname = "test" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "./test.v:1.1-48.10" *)
module test();
  (* src = "./test.v:27.27-27.71|./IO_map.v:9.23-9.24" *)
  wire _00_;
  (* src = "./test.v:27.27-27.71|./IO_map.v:10.24-10.25" *)
  wire _01_;
  (* src = "./test.v:28.27-28.65|./IO_map.v:9.23-9.24" *)
  wire _02_;
  (* src = "./test.v:28.27-28.65|./IO_map.v:10.24-10.25" *)
  wire _03_;
  (* src = "./test.v:29.27-29.65|./IO_map.v:9.23-9.24" *)
  wire _04_;
  (* src = "./test.v:29.27-29.65|./IO_map.v:10.24-10.25" *)
  wire _05_;
  (* src = "./test.v:33.26-33.51|./IO_map.v:9.23-9.24" *)
  wire _06_;
  (* src = "./test.v:33.26-33.51|./IO_map.v:10.24-10.25" *)
  wire _07_;
  (* src = "./test.v:34.26-34.51|./IO_map.v:9.23-9.24" *)
  wire _08_;
  (* src = "./test.v:34.26-34.51|./IO_map.v:10.24-10.25" *)
  wire _09_;
  (* src = "./test.v:37.26-37.43|./IO_map.v:9.23-9.24" *)
  wire _10_;
  (* src = "./test.v:37.26-37.43|./IO_map.v:10.24-10.25" *)
  wire _11_;
  (* src = "./test.v:44.26-44.43|./IO_map.v:9.23-9.24" *)
  wire _12_;
  (* src = "./test.v:44.26-44.43|./IO_map.v:10.24-10.25" *)
  wire _13_;
  (* src = "./test.v:36.39-36.81|./const_map.v:10.22-10.23" *)
  wire _14_;
  (* src = "./test.v:39.37-39.75|./const_map.v:10.22-10.23" *)
  wire _15_;
  (* src = "./test.v:42.37-42.79|./const_map.v:10.22-10.23" *)
  wire _16_;
  (* src = "./test.v:32.44-32.115|./PE_map.v:9.23-9.24" *)
  wire _17_;
  (* src = "./test.v:32.44-32.115|./PE_map.v:10.23-10.24" *)
  wire _18_;
  (* src = "./test.v:32.44-32.115|./PE_map.v:11.23-11.24" *)
  wire _19_;
  (* src = "./test.v:32.44-32.115|./PE_map.v:12.24-12.25" *)
  wire _20_;
  (* src = "./test.v:30.24-30.74|./reg_map.v:9.22-9.23" *)
  wire _21_;
  (* src = "./test.v:31.24-31.78|./reg_map.v:9.22-9.23" *)
  wire _22_;
  (* src = "./test.v:45.44-45.114|./PE_map.v:9.23-9.24" *)
  wire _23_;
  (* src = "./test.v:45.44-45.114|./PE_map.v:10.23-10.24" *)
  wire _24_;
  (* src = "./test.v:45.44-45.114|./PE_map.v:11.23-11.24" *)
  wire _25_;
  (* src = "./test.v:45.44-45.114|./PE_map.v:12.24-12.25" *)
  wire _26_;
  (* src = "./test.v:35.40-35.104|./PE_map.v:9.23-9.24" *)
  wire _27_;
  (* src = "./test.v:35.40-35.104|./PE_map.v:10.23-10.24" *)
  wire _28_;
  (* src = "./test.v:35.40-35.104|./PE_map.v:11.23-11.24" *)
  wire _29_;
  (* src = "./test.v:35.40-35.104|./PE_map.v:12.24-12.25" *)
  wire _30_;
  (* src = "./test.v:38.40-38.103|./PE_map.v:9.23-9.24" *)
  wire _31_;
  (* src = "./test.v:38.40-38.103|./PE_map.v:10.23-10.24" *)
  wire _32_;
  (* src = "./test.v:38.40-38.103|./PE_map.v:11.23-11.24" *)
  wire _33_;
  (* src = "./test.v:38.40-38.103|./PE_map.v:12.24-12.25" *)
  wire _34_;
  (* src = "./test.v:40.39-40.95|./PE_map.v:9.23-9.24" *)
  wire _35_;
  (* src = "./test.v:40.39-40.95|./PE_map.v:10.23-10.24" *)
  wire _36_;
  (* src = "./test.v:40.39-40.95|./PE_map.v:11.23-11.24" *)
  wire _37_;
  (* src = "./test.v:40.39-40.95|./PE_map.v:12.24-12.25" *)
  wire _38_;
  (* src = "./test.v:41.40-41.107|./PE_map.v:9.23-9.24" *)
  wire _39_;
  (* src = "./test.v:41.40-41.107|./PE_map.v:10.23-10.24" *)
  wire _40_;
  (* src = "./test.v:41.40-41.107|./PE_map.v:11.23-11.24" *)
  wire _41_;
  (* src = "./test.v:41.40-41.107|./PE_map.v:12.24-12.25" *)
  wire _42_;
  (* src = "./test.v:43.40-43.101|./PE_map.v:9.23-9.24" *)
  wire _43_;
  (* src = "./test.v:43.40-43.101|./PE_map.v:10.23-10.24" *)
  wire _44_;
  (* src = "./test.v:43.40-43.101|./PE_map.v:11.23-11.24" *)
  wire _45_;
  (* src = "./test.v:43.40-43.101|./PE_map.v:12.24-12.25" *)
  wire _46_;
  (* src = "./test.v:46.46-46.125|./PE_map.v:9.23-9.24" *)
  wire _47_;
  (* src = "./test.v:46.46-46.125|./PE_map.v:10.23-10.24" *)
  wire _48_;
  (* src = "./test.v:46.46-46.125|./PE_map.v:11.23-11.24" *)
  wire _49_;
  (* src = "./test.v:46.46-46.125|./PE_map.v:12.24-12.25" *)
  wire _50_;
  (* src = "./test.v:26.27-26.51|./IO_map.v:9.23-9.24" *)
  wire _51_;
  (* src = "./test.v:26.27-26.51|./IO_map.v:10.24-10.25" *)
  wire _52_;
  (* src = "./test.v:15.17-15.20" *)
  wire i_0;
  (* src = "./test.v:20.17-20.20" *)
  wire i_4;
  (* src = "./test.v:11.17-11.29" *)
  wire i_arrayidx18;
  (* src = "./test.v:21.17-21.31" *)
  wire i_arrayidx19_0;
  (* src = "./test.v:25.17-25.31" *)
  wire i_arrayidx19_1;
  (* src = "./test.v:22.17-22.24" *)
  wire i_cmp21;
  (* src = "./test.v:14.17-14.30" *)
  wire i_cmp21_const;
  (* src = "./test.v:10.17-10.36" *)
  wire i_cnt_160_reg2mem28;
  (* src = "./test.v:23.17-23.34" *)
  wire i_cnt_2_reg2mem26;
  (* src = "./test.v:9.17-9.34" *)
  wire i_e_061_reg2mem30;
  (* src = "./test.v:12.17-12.24" *)
  wire i_edges;
  (* src = "./test.v:24.17-24.31" *)
  wire i_exitcond_not;
  (* src = "./test.v:16.17-16.22" *)
  wire i_inc;
  (* src = "./test.v:18.17-18.24" *)
  wire i_inc27;
  (* src = "./test.v:19.17-19.30" *)
  wire i_inc27_const;
  (* src = "./test.v:17.17-17.28" *)
  wire i_inc_const;
  (* src = "./test.v:13.17-13.24" *)
  wire i_level;
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:37.26-37.43|./IO_map.v:20.15-22.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) inst_i_0 (
    .to_fabric(i_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:44.26-44.43|./IO_map.v:20.15-22.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) inst_i_4 (
    .to_fabric(i_4)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:32.44-32.115|./PE_map.v:32.15-36.14" *)
  ALU #(
    .OP(32'sd1),
    .WIDTH(32'sd1)
  ) inst_i_arrayidx18 (
    .data_in1(i_edges),
    .data_in2(i_e_061_reg2mem30),
    .data_out(i_arrayidx18)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:45.44-45.114|./PE_map.v:32.15-36.14" *)
  ALU #(
    .OP(32'sd1),
    .WIDTH(32'sd1)
  ) inst_i_arrayidx19_0 (
    .data_in1(i_level),
    .data_in2(i_arrayidx18),
    .data_out(i_arrayidx19_0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:46.46-46.125|./PE_map.v:41.15-46.14" *)
  ALU #(
    .OP(32'sd0),
    .WIDTH(32'sd1)
  ) inst_i_arrayidx19_1 (
    .data_in1(i_arrayidx18),
    .data_in2(i_level),
    .data_in3(i_0),
    .data_out(i_arrayidx19_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:35.40-35.104|./PE_map.v:32.15-36.14" *)
  ALU #(
    .OP(32'sd2),
    .WIDTH(32'sd1)
  ) inst_i_cmp21 (
    .data_in1(i_arrayidx19_0),
    .data_in2(i_cmp21_const),
    .data_out(i_cmp21)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:40.39-40.95|./PE_map.v:24.15-27.14" *)
  ALU #(
    .OP(32'sd4),
    .WIDTH(32'sd1)
  ) inst_i_cnt_2_reg2mem26 (
    .data_in1(i_inc),
    .data_out(i_cnt_2_reg2mem26)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:33.26-33.51|./IO_map.v:20.15-22.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) inst_i_edges (
    .to_fabric(i_edges)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:43.40-43.101|./PE_map.v:32.15-36.14" *)
  ALU #(
    .OP(32'sd2),
    .WIDTH(32'sd1)
  ) inst_i_exitcond_not (
    .data_in1(i_inc27),
    .data_in2(i_4),
    .data_out(i_exitcond_not)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:38.40-38.103|./PE_map.v:32.15-36.14" *)
  ALU #(
    .OP(32'sd3),
    .WIDTH(32'sd1)
  ) inst_i_inc (
    .data_in1(i_cnt_160_reg2mem28),
    .data_in2(i_inc_const),
    .data_out(i_inc)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:41.40-41.107|./PE_map.v:32.15-36.14" *)
  ALU #(
    .OP(32'sd3),
    .WIDTH(32'sd1)
  ) inst_i_inc27 (
    .data_in1(i_e_061_reg2mem30),
    .data_in2(i_inc27_const),
    .data_out(i_inc27)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:34.26-34.51|./IO_map.v:20.15-22.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) inst_i_level (
    .to_fabric(i_level)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:36.39-36.81|./const_map.v:13.20-13.53" *)
  const_unit inst_inst_i_cmp21_const (
    .const_out(i_cmp21_const)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:31.24-31.78|./reg_map.v:12.18-12.49" *)
  reg_unit inst_inst_i_cnt_160_reg2mem28 (
    .reg_out(i_cnt_160_reg2mem28)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:30.24-30.74|./reg_map.v:12.18-12.49" *)
  reg_unit inst_inst_i_e_061_reg2mem30 (
    .reg_out(i_e_061_reg2mem30)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:42.37-42.79|./const_map.v:13.20-13.53" *)
  const_unit inst_inst_i_inc27_const (
    .const_out(i_inc27_const)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:39.37-39.75|./const_map.v:13.20-13.53" *)
  const_unit inst_inst_i_inc_const (
    .const_out(i_inc_const)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:29.27-29.65|./IO_map.v:26.15-28.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) out_i_arrayidx19_1 (
    .from_fabric(i_arrayidx19_1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:26.27-26.51|./IO_map.v:26.15-28.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) out_i_cmp21 (
    .from_fabric(i_cmp21)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:27.27-27.71|./IO_map.v:26.15-28.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) out_i_cnt_2_reg2mem26 (
    .from_fabric(i_cnt_2_reg2mem26)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./test.v:28.27-28.65|./IO_map.v:26.15-28.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) out_i_exitcond_not (
    .from_fabric(i_exitcond_not)
  );
endmodule
