/* Generated by Yosys 0.47+56 (git sha1 a22ff47d6, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:1.1-17.10" *)
module test();
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:11.40-11.71|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:9.23-9.24" *)
  wire _00_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:11.40-11.71|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:10.23-10.24" *)
  wire _01_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:11.40-11.71|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:11.23-11.24" *)
  wire _02_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:11.40-11.71|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:12.24-12.25" *)
  wire _03_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:12.40-12.69|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:9.23-9.24" *)
  wire _04_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:12.40-12.69|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:10.23-10.24" *)
  wire _05_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:12.40-12.69|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:11.23-11.24" *)
  wire _06_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:12.40-12.69|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:12.24-12.25" *)
  wire _07_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:10.27-10.39|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:9.23-9.24" *)
  wire _08_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:10.27-10.39|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:10.24-10.25" *)
  wire _09_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:13.26-13.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:9.23-9.24" *)
  wire _10_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:13.26-13.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:10.24-10.25" *)
  wire _11_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:14.26-14.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:9.23-9.24" *)
  wire _12_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:14.26-14.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:10.24-10.25" *)
  wire _13_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:15.26-15.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:9.23-9.24" *)
  wire _14_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:15.26-15.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:10.24-10.25" *)
  wire _15_;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:5.17-5.18" *)
  wire a;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:9.17-9.18" *)
  wire b;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:6.17-6.20" *)
  wire inA;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:7.17-7.20" *)
  wire inB;
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:8.17-8.20" *)
  wire inC;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:11.40-11.71|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:35.15-39.14" *)
  ALU #(
    .OP(32'sd0),
    .WIDTH(32'sd1)
  ) inst_a (
    .data_in1(inA),
    .data_in2(inB),
    .data_out(a)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:12.40-12.69|/home/kelvin/FABulous_fork/myProject/PnR/PE_map.v:35.15-39.14" *)
  ALU #(
    .OP(32'sd0),
    .WIDTH(32'sd1)
  ) inst_b (
    .data_in1(a),
    .data_in2(inC),
    .data_out(b)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:13.26-13.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:20.15-22.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) inst_inA (
    .to_fabric(inA)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:14.26-14.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:20.15-22.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) inst_inB (
    .to_fabric(inB)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:15.26-15.43|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:20.15-22.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) inst_inC (
    .to_fabric(inC)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/kelvin/FABulous_fork/myProject/PnR/test.v:10.27-10.39|/home/kelvin/FABulous_fork/myProject/PnR/IO_map.v:26.15-28.14" *)
  IO #(
    .WIDTH(32'sd1)
  ) out_b (
    .from_fabric(b)
  );
endmodule
