from FABulous.fabric_definition.SwitchMatrix import MuxPort
from FABulous.fabric_definition.define import IO, Side
from FABulous.fabric_definition.Port import TilePort, Port, BelPort

class LUT4AB_ports:
    def __init__(self):
        # tile ports
        self.N1BEG = MuxPort(TilePort(name='N1BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.N1END = MuxPort(TilePort(name='N1END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.N2BEG = MuxPort(TilePort(name='N2BEG', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.N2MID = MuxPort(TilePort(name='N2MID', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.N2BEGb = MuxPort(TilePort(name='N2BEGb', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.N2END = MuxPort(TilePort(name='N2END', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.N4BEG = MuxPort(TilePort(name='N4BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.N4END = MuxPort(TilePort(name='N4END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.NN4BEG = MuxPort(TilePort(name='NN4BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.NN4END = MuxPort(TilePort(name='NN4END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.E1BEG = MuxPort(TilePort(name='E1BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.E1END = MuxPort(TilePort(name='E1END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.E2BEG = MuxPort(TilePort(name='E2BEG', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.E2MID = MuxPort(TilePort(name='E2MID', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.E2BEGb = MuxPort(TilePort(name='E2BEGb', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.E2END = MuxPort(TilePort(name='E2END', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.EE4BEG = MuxPort(TilePort(name='EE4BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.EE4END = MuxPort(TilePort(name='EE4END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.E6BEG = MuxPort(TilePort(name='E6BEG', ioDirection=IO.OUTPUT, wireCount=2, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=2)
        self.E6END = MuxPort(TilePort(name='E6END', ioDirection=IO.INPUT, wireCount=2, isBus=False, sideOfTile=Side.EAST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=2)
        self.S1BEG = MuxPort(TilePort(name='S1BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.S1END = MuxPort(TilePort(name='S1END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.S2BEG = MuxPort(TilePort(name='S2BEG', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.S2MID = MuxPort(TilePort(name='S2MID', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.S2BEGb = MuxPort(TilePort(name='S2BEGb', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.S2END = MuxPort(TilePort(name='S2END', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.S4BEG = MuxPort(TilePort(name='S4BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.S4END = MuxPort(TilePort(name='S4END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.SS4BEG = MuxPort(TilePort(name='SS4BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.SS4END = MuxPort(TilePort(name='SS4END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.SOUTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.W1BEG = MuxPort(TilePort(name='W1BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.W1END = MuxPort(TilePort(name='W1END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.W2BEG = MuxPort(TilePort(name='W2BEG', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.W2MID = MuxPort(TilePort(name='W2MID', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.W2BEGb = MuxPort(TilePort(name='W2BEGb', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.W2END = MuxPort(TilePort(name='W2END', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.WW4BEG = MuxPort(TilePort(name='WW4BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.WW4END = MuxPort(TilePort(name='WW4END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.W6BEG = MuxPort(TilePort(name='W6BEG', ioDirection=IO.OUTPUT, wireCount=2, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=2)
        self.W6END = MuxPort(TilePort(name='W6END', ioDirection=IO.INPUT, wireCount=2, isBus=False, sideOfTile=Side.WEST, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=2)
        self.J2MID_ABa_BEG = MuxPort(TilePort(name='J2MID_ABa_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_ABa_END = MuxPort(TilePort(name='J2MID_ABa_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_CDa_BEG = MuxPort(TilePort(name='J2MID_CDa_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_CDa_END = MuxPort(TilePort(name='J2MID_CDa_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_EFa_BEG = MuxPort(TilePort(name='J2MID_EFa_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_EFa_END = MuxPort(TilePort(name='J2MID_EFa_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_GHa_BEG = MuxPort(TilePort(name='J2MID_GHa_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_GHa_END = MuxPort(TilePort(name='J2MID_GHa_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_ABb_BEG = MuxPort(TilePort(name='J2MID_ABb_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_ABb_END = MuxPort(TilePort(name='J2MID_ABb_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_CDb_BEG = MuxPort(TilePort(name='J2MID_CDb_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_CDb_END = MuxPort(TilePort(name='J2MID_CDb_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_EFb_BEG = MuxPort(TilePort(name='J2MID_EFb_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_EFb_END = MuxPort(TilePort(name='J2MID_EFb_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_GHb_BEG = MuxPort(TilePort(name='J2MID_GHb_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2MID_GHb_END = MuxPort(TilePort(name='J2MID_GHb_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2END_AB_BEG = MuxPort(TilePort(name='J2END_AB_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2END_AB_END = MuxPort(TilePort(name='J2END_AB_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2END_CD_BEG = MuxPort(TilePort(name='J2END_CD_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2END_CD_END = MuxPort(TilePort(name='J2END_CD_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2END_EF_BEG = MuxPort(TilePort(name='J2END_EF_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2END_EF_END = MuxPort(TilePort(name='J2END_EF_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2END_GH_BEG = MuxPort(TilePort(name='J2END_GH_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J2END_GH_END = MuxPort(TilePort(name='J2END_GH_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.JN2BEG = MuxPort(TilePort(name='JN2BEG', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.JN2END = MuxPort(TilePort(name='JN2END', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.JE2BEG = MuxPort(TilePort(name='JE2BEG', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.JE2END = MuxPort(TilePort(name='JE2END', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.JS2BEG = MuxPort(TilePort(name='JS2BEG', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.JS2END = MuxPort(TilePort(name='JS2END', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.JW2BEG = MuxPort(TilePort(name='JW2BEG', ioDirection=IO.OUTPUT, wireCount=8, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.JW2END = MuxPort(TilePort(name='JW2END', ioDirection=IO.INPUT, wireCount=8, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=8)
        self.J_l_AB_BEG = MuxPort(TilePort(name='J_l_AB_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J_l_AB_END = MuxPort(TilePort(name='J_l_AB_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J_l_CD_BEG = MuxPort(TilePort(name='J_l_CD_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J_l_CD_END = MuxPort(TilePort(name='J_l_CD_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J_l_EF_BEG = MuxPort(TilePort(name='J_l_EF_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J_l_EF_END = MuxPort(TilePort(name='J_l_EF_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J_l_GH_BEG = MuxPort(TilePort(name='J_l_GH_BEG', ioDirection=IO.OUTPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.J_l_GH_END = MuxPort(TilePort(name='J_l_GH_END', ioDirection=IO.INPUT, wireCount=4, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=4)
        self.NULL = MuxPort(TilePort(name='NULL', ioDirection=IO.OUTPUT, wireCount=1, isBus=False, sideOfTile=Side.ANY, terminal=True, spanning=False), isTilePort=True, isBus=False, bitWidth=1)
        self.GND = MuxPort(TilePort(name='GND', ioDirection=IO.INPUT, wireCount=1, isBus=False, sideOfTile=Side.ANY, terminal=True, spanning=False), isTilePort=True, isBus=False, bitWidth=1)
        self.VCC = MuxPort(TilePort(name='VCC', ioDirection=IO.INPUT, wireCount=1, isBus=False, sideOfTile=Side.ANY, terminal=True, spanning=False), isTilePort=True, isBus=False, bitWidth=1)
        self.Co = MuxPort(TilePort(name='Co', ioDirection=IO.OUTPUT, wireCount=1, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=1)
        self.Ci = MuxPort(TilePort(name='Ci', ioDirection=IO.INPUT, wireCount=1, isBus=False, sideOfTile=Side.NORTH, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=1)
        self.J_SR_BEG = MuxPort(TilePort(name='J_SR_BEG', ioDirection=IO.OUTPUT, wireCount=1, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=1)
        self.J_SR_END = MuxPort(TilePort(name='J_SR_END', ioDirection=IO.INPUT, wireCount=1, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=1)
        self.J_EN_BEG = MuxPort(TilePort(name='J_EN_BEG', ioDirection=IO.OUTPUT, wireCount=1, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=1)
        self.J_EN_END = MuxPort(TilePort(name='J_EN_END', ioDirection=IO.INPUT, wireCount=1, isBus=False, sideOfTile=Side.ANY, terminal=False, spanning=False), isTilePort=True, isBus=False, bitWidth=1)

        # bel ports
        self.LA_ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=19, isBus=False, prefix='LA_', external=False), isBelPort=True, isBus=False, bitWidth=19)
        self.LB_ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=19, isBus=False, prefix='LB_', external=False), isBelPort=True, isBus=False, bitWidth=19)
        self.LC_ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=19, isBus=False, prefix='LC_', external=False), isBelPort=True, isBus=False, bitWidth=19)
        self.LD_ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=19, isBus=False, prefix='LD_', external=False), isBelPort=True, isBus=False, bitWidth=19)
        self.LE_ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=19, isBus=False, prefix='LE_', external=False), isBelPort=True, isBus=False, bitWidth=19)
        self.LF_ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=19, isBus=False, prefix='LF_', external=False), isBelPort=True, isBus=False, bitWidth=19)
        self.LG_ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=19, isBus=False, prefix='LG_', external=False), isBelPort=True, isBus=False, bitWidth=19)
        self.LH_ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=19, isBus=False, prefix='LH_', external=False), isBelPort=True, isBus=False, bitWidth=19)
        self.ConfigBits = MuxPort(BelPort(name='ConfigBits', ioDirection=IO.INPUT, wireCount=2, isBus=False, prefix='', external=False), isBelPort=True, isBus=False, bitWidth=2)

    def NewWire(self, srcName: str, dstName: str, wireCount: int) -> tuple[MuxPort, MuxPort]:
        portSrc = MuxPort(Port(name=srcName, ioDirection=IO.INPUT, wireCount=wireCount, isBus=False), bitWidth=wireCount, isCreated=True)
        setattr(self, srcName, portSrc)
        portDst = MuxPort(Port(name=dstName, ioDirection=IO.OUTPUT, wireCount=wireCount, isBus=False), bitWidth=wireCount, isCreated=True)
        setattr(self, dstName, portDst)
        return portSrc, portDst

    def __getitem__(self, key: str) -> MuxPort:
        return getattr(self, key)

    def __setitem__(self, key: str, value: MuxPort):
        pass