/* Generated by Yosys 0.50 (git sha1 b5170e139, g++ 12.2.1 -fPIC -O3) */

module ALU_ALU_func_0(clk, data_in1, data_in2, data_in3, data_out, ALU_func);
  input [2:0] ALU_func;
  wire [2:0] ALU_func;
  input clk;
  wire clk;
  input [31:0] data_in1;
  wire [31:0] data_in1;
  input [31:0] data_in2;
  wire [31:0] data_in2;
  input [31:0] data_in3;
  wire [31:0] data_in3;
  output [31:0] data_out;
  wire [31:0] data_out;
  assign data_out = data_in1 + data_in2;
  assign ALU_func = 3'h0;
endmodule

/* Generated by Yosys 0.50 (git sha1 b5170e139, g++ 12.2.1 -fPIC -O3) */

module ALU_ALU_func_1(clk, data_in1, data_in2, data_in3, data_out, ALU_func);
  input [2:0] ALU_func;
  wire [2:0] ALU_func;
  input clk;
  wire clk;
  input [31:0] data_in1;
  wire [31:0] data_in1;
  input [31:0] data_in2;
  wire [31:0] data_in2;
  input [31:0] data_in3;
  wire [31:0] data_in3;
  output [31:0] data_out;
  wire [31:0] data_out;
  assign data_out = data_in1 - data_in2;
  assign ALU_func = 3'h1;
endmodule

/* Generated by Yosys 0.50 (git sha1 b5170e139, g++ 12.2.1 -fPIC -O3) */

module ALU_ALU_func_2(clk, data_in1, data_in2, data_in3, data_out, ALU_func);
  input [2:0] ALU_func;
  wire [2:0] ALU_func;
  input clk;
  wire clk;
  input [31:0] data_in1;
  wire [31:0] data_in1;
  input [31:0] data_in2;
  wire [31:0] data_in2;
  input [31:0] data_in3;
  wire [31:0] data_in3;
  output [31:0] data_out;
  wire [31:0] data_out;
  assign data_out = data_in1 & data_in2;
  assign ALU_func = 3'h2;
endmodule

/* Generated by Yosys 0.50 (git sha1 b5170e139, g++ 12.2.1 -fPIC -O3) */

module ALU_ALU_func_3(clk, data_in1, data_in2, data_in3, data_out, ALU_func);
  input [2:0] ALU_func;
  wire [2:0] ALU_func;
  input clk;
  wire clk;
  input [31:0] data_in1;
  wire [31:0] data_in1;
  input [31:0] data_in2;
  wire [31:0] data_in2;
  input [31:0] data_in3;
  wire [31:0] data_in3;
  output [31:0] data_out;
  wire [31:0] data_out;
  assign data_out = data_in1 | data_in2;
  assign ALU_func = 3'h3;
endmodule

/* Generated by Yosys 0.50 (git sha1 b5170e139, g++ 12.2.1 -fPIC -O3) */

module ALU_ALU_func_4(clk, data_in1, data_in2, data_in3, data_out, ALU_func);
  input [2:0] ALU_func;
  wire [2:0] ALU_func;
  input clk;
  wire clk;
  input [31:0] data_in1;
  wire [31:0] data_in1;
  input [31:0] data_in2;
  wire [31:0] data_in2;
  input [31:0] data_in3;
  wire [31:0] data_in3;
  output [31:0] data_out;
  wire [31:0] data_out;
  assign data_out = data_in1 ^ data_in2;
  assign ALU_func = 3'h4;
endmodule

/* Generated by Yosys 0.50 (git sha1 b5170e139, g++ 12.2.1 -fPIC -O3) */

module ALU_ALU_func_5(clk, data_in1, data_in2, data_in3, data_out, ALU_func);
  input [2:0] ALU_func;
  wire [2:0] ALU_func;
  input clk;
  wire clk;
  input [31:0] data_in1;
  wire [31:0] data_in1;
  input [31:0] data_in2;
  wire [31:0] data_in2;
  input [31:0] data_in3;
  wire [31:0] data_in3;
  output [31:0] data_out;
  wire [31:0] data_out;
  assign data_out = data_in1 * data_in2;
  assign ALU_func = 3'h5;
endmodule

