/* Generated by Yosys 0.50 (git sha1 b5170e139, g++ 12.2.1 -fPIC -O3) */

module IO(from_fabric, to_fabric, in, out, ConfigBits);
  input ConfigBits;
  wire ConfigBits;
  input from_fabric;
  wire from_fabric;
  input in;
  wire in;
  output out;
  wire out;
  output to_fabric;
  wire to_fabric;
  assign out = from_fabric;
  assign to_fabric = in;
endmodule
