name: Prepare FABulous workflow
description: Composite action to prepare a container with everything needed to run FABulous

inputs:
  python_version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  additional_system_packages:
    description: 'Additional ubuntu packages to install'
    required: false
    default: ''
  additional_python_packages:
    description: 'Additional python packages to install'
    required: false
    default: ''
  install_GHDL_mcode:
    description: 'Install GHDL with mcode backend'
    required: false
    default: false

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
    - name: Install iverilog and yosys from apt
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y iverilog yosys nextpnr-generic
    - name: Install GHDL mcode nightly
      # GHDL mcode is required to test our fabric.
      # The oss-cad-suite action installs GHDL, but with the LLVM backend, which is much slower for our simulation
      if: ${{ inputs.install_GHDL_mcode == true }}
      uses: ghdl/setup-ghdl@v1
      with:
        version: nightly
        backend: mcode
        investigate: true
    - name: Install GHDL-Yosys plugin
      if: ${{ inputs.install_GHDL_mcode == true }}
      shell: bash
      run: |
        # Install dependencies for building the plugin
        sudo apt-get install -y build-essential
        # Clone and build ghdl-yosys-plugin
        git clone https://github.com/ghdl/ghdl-yosys-plugin.git
        cd ghdl-yosys-plugin
        # Set up environment for GHDL
        export PATH="/opt/ghdl/bin:$PATH"
        make
        sudo make install
    - name: Install additional ubuntu packages
      if: ${{ inputs.additional_system_packages != '' }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.additional_system_packages }}
    - name: Upgrade pip
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
    - name: Install additional python packages
      if: ${{ inputs.additional_python_packages != '' }}
      shell: bash
      run: |
        pip3 install ${{ inputs.additional_python_packages }}
    - name: Install FABulous requirements.txt
      shell: bash
      run: |
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Install FABulous requirements
      shell: bash
      run: |
        pip3 install -e .
