import argparse
import os
from pathlib import Path

from loguru import logger

from FABulous.FABulous_CLI.FABulous_CLI import FABulous_CLI
from FABulous.FABulous_CLI.helper import (
    create_project,
    install_oss_cad_suite,
    setup_global_env_vars,
    setup_logger,
    setup_project_env_vars,
)


def main():
    """Main function to start the command line interface of FABulous, sets up argument
    parsing, initialises required components and handles start the FABulous CLI.

    Also logs terminal output and if .FABulous folder is missing.

    Command line arguments
    ----------------------
    project_dir : str
        Directory path to project folder.
    -c, --createProject :  bool
        Flag to create new project.
    -fs, --FABulousScript: str, optional
        Run FABulous with a FABulous script.
    -ts, --TCLscript: str, optional
        Run FABulous with a TCL script.
    -log : str, optional
        Log all the output from the terminal.
    -w, --writer : <'verilog', 'vhdl'>, optional
        Set type of HDL code generated. Currently supports .V and .VHDL (Default .V)
    -md, --metaDataDir : str, optional
        Set output directory for metadata files, e.g. pip.txt, bel.txt
    -v, --verbose : bool, optional
        Show detailed log information including function and line number.
    -gde, --globalDotEnv : str, optional
        Set global .env file path. Default is $FAB_ROOT/.env
    -pde, --projectDotEnv : str, optional
        Set project .env file path. Default is $FAB_PROJ_DIR/.env
    -iocd, --install_oss_cad_suite : str, optional
        Install the oss-cad-suite in the project directory.
    """
    parser = argparse.ArgumentParser(
        description="The command line interface for FABulous"
    )

    create_group = parser.add_mutually_exclusive_group()

    create_group.add_argument(
        "-c",
        "--createProject",
        default=False,
        action="store_true",
        help="Create a new project",
    )

    create_group.add_argument(
        "-iocs",
        "--install_oss_cad_suite",
        help="Install the oss-cad-suite in the directory."
        "This will create a new directory called oss-cad-suite in the provided"
        "directory and install the oss-cad-suite there."
        "If there is already a directory called oss-cad-suite, it will be removed and replaced with a new one."
        "This will also automatically add the FAB_OSS_CAD_SUITE env var in the global FABulous .env file. ",
        action="store_true",
        default=False,
    )

    script_group = parser.add_mutually_exclusive_group()

    parser.add_argument(
        "project_dir",
        default="",
        nargs="?",
        help="The directory to the project folder",
    )

    script_group.add_argument(
        "-fs",
        "--FABulousScript",
        default=None,
        help="Run FABulous with a FABulous script. A FABulous script is a text file containing only FABulous commands"
        "This will automatically exit the CLI once the command finish execution, and the exit will always happen gracefully.",
        nargs=1,
        type=Path,
    )

    script_group.add_argument(
        "-ts",
        "--TCLScript",
        default=None,
        help="Run FABulous with a TCL script. A TCL script is a text file containing a mix of TCL commands and FABulous commands."
        "This will automatically exit the CLI once the command finish execution, and the exit will always happen gracefully.",
        nargs=1,
        type=Path,
    )

    script_group.add_argument(
        "-p",
        "--commands",
        nargs=1,
        help="execute <commands> (to chain commands, separate them with semicolon + whitespace: 'cmd1; cmd2')",
    )

    parser.add_argument(
        "-log",
        default="",
        type=Path,
        nargs="?",
        const="FABulous.log",
        help="Log all the output from the terminal",
    )

    parser.add_argument(
        "-w",
        "--writer",
        choices=["verilog", "vhdl"],
        help="Set the type of HDL code generated by the tool. Currently support Verilog and VHDL (Default using Verilog)",
    )

    parser.add_argument(
        "-md",
        "--metaDataDir",
        default=".FABulous",
        nargs=1,
        help="Set the output directory for the meta data files eg. pip.txt, bel.txt",
    )

    parser.add_argument(
        "-v",
        "--verbose",
        default=False,
        action="count",
        help="Show detailed log information including function and line number. For -vv additionally output from "
        "FABulator is logged to the shell for the start_FABulator command",
    )

    parser.add_argument(
        "-gde",
        "--globalDotEnv",
        nargs=1,
        help="Set the global .env file path. Default is $FAB_ROOT/.env",
    )

    parser.add_argument(
        "-pde",
        "--projectDotEnv",
        nargs=1,
        help="Set the project .env file path. Default is $FAB_PROJ_DIR/.env",
    )

    parser.add_argument(
        "--force",
        action="store_true",
        help="Force the command to run and ignore any errors. This feature does not work for the TCLScript argument",
    )

    parser.add_argument("--debug", action="store_true", help="Enable debug mode")

    args = parser.parse_args()

    setup_logger(args.verbose, args.debug, log_file=args.log)

    # Start with default value
    projectDir = Path().cwd()

    # Setup global and project env vars to load .env files
    setup_global_env_vars(args)
    setup_project_env_vars(args)

    # Check if FAB_PROJ_DIR is set in environment (including from .env files)
    if fab_proj_dir := os.getenv("FAB_PROJ_DIR", None):
        projectDir = Path(fab_proj_dir).absolute().resolve()

    # Finally, user provided argument takes highest priority
    if args.project_dir:
        projectDir = Path(args.project_dir).absolute().resolve()

    if args.createProject:
        create_project(projectDir, args.writer)
        exit(0)

    if args.install_oss_cad_suite:
        install_oss_cad_suite(projectDir, True)
        exit(0)

    if not (projectDir / ".FABulous").exists():
        logger.error(
            "The directory provided is not a FABulous project as it does not have a .FABulous folder"
        )
        exit(1)

    if not projectDir.exists():
        logger.error(f"The directory provided does not exist: {projectDir}")
        exit(1)

    fab_CLI = FABulous_CLI(
        os.getenv("FAB_PROJ_LANG"),
        projectDir,
        Path().cwd(),
        force=args.force,
    )
    fab_CLI.debug = args.debug
    fabScript: None | Path = None
    tclScript: None | Path = None
    if args.FABulousScript:
        fabScript = args.FABulousScript[0].absolute()
    if args.TCLScript:
        tclScript = args.TCLScript[0].absolute()

    logger.info(f"Setting current working directory to: {projectDir}")
    os.chdir(projectDir)
    fab_CLI.onecmd_plus_hooks("load_fabric")

    if commands := args.commands:
        commands = [i for i in commands[0].split("; ") if i.strip()]
        for c in commands:
            fab_CLI.onecmd_plus_hooks(c)
            if fab_CLI.exit_code and not args.force:
                logger.error(
                    f"Command '{c}' execution failed with exit code {fab_CLI.exit_code}"
                )
                exit(fab_CLI.exit_code)
        else:
            logger.info(
                f'Commands "{"; ".join(i.strip() for i in commands)}" executed successfully'
            )
            exit(fab_CLI.exit_code)

    elif fabScript is not None:
        fab_CLI.onecmd_plus_hooks(f"run_script {fabScript}")
        if fab_CLI.exit_code:
            logger.error(
                f"FABulous script {args.FABulousScript} execution failed with exit code {fab_CLI.exit_code}"
            )
        else:
            logger.info(f"FABulous script {args.FABulousScript} executed successfully")
        exit(fab_CLI.exit_code)

    elif tclScript is not None:
        fab_CLI.onecmd_plus_hooks(f"run_tcl {tclScript}")
        if fab_CLI.exit_code:
            logger.error(
                f"TCL script {args.TCLScript} execution failed with exit code {fab_CLI.exit_code}"
            )
        else:
            logger.info(f"TCL script {args.TCLScript} executed successfully")
        exit(fab_CLI.exit_code)

    else:
        fab_CLI.interactive = True
        if args.verbose == 2:
            fab_CLI.verbose = True

        fab_CLI.cmdloop()
        exit(0)


if __name__ == "__main__":
    main()
