name: HDL linting

on: [pull_request]

jobs:

  format-verilog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare_FABulous_container
    - uses: chipsalliance/verible-formatter-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
  lint-verilog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: chipsalliance/verible-linter-action@main
      with:
        config_file: 'config.rule'
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Verilog Linter
      run: |
        FABulous -c demo
        verilator --lint-only demo/**/*.v

  lint-vhdl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prepare_FABulous_container
    - name: Run VHDL Linter
      run: | 
        FABulous -c demo_vhdl -w vhdl
        ghdl -s --std=08 demo_vhdl/**/*.vhdl