name: Testing with pytest and cocotb

on: [push, pull_request]


jobs:
  run_pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/prepare_FABulous_container
        with:
          additional_system_packages: "iverilog"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run pytest
        run: |
          export PATH="/usr/bin:$PATH"
          pytest -v -x